### PR TITLE
Update DigitalOcean to stable release

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Working on moving the one-click to the stable release

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Ready for image update, this can be merged whenever.

@pierreburgy when you have a moment reach out to me on slack

**Review by alexandrebodin — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
Pending speaking with @pierreburgy to build the image and submit to DO for approval

**Comment by derrickmehaffy** [comment]
Image submitted, merging PR

**Pull request merged**
